values: Values

prep: Preprocessor {
  ident: Identity
  simple: Simple Packing
  scale: Scaling
  custom: ...
}

analyser: Analyser {
  bitinfo: BitInformation
  custom: ...
}

inf_cont: Mask

values -> prep -> analyser -> inf_cont
